/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OrganogramaRouteImport } from './routes/organograma'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as IdentidadeRouteImport } from './routes/identidade'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as AutoriaRouteImport } from './routes/autoria'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as ADMCMFRouteImport } from './routes/ADMCMF'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth/discord.callback'

const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganogramaRoute = OrganogramaRouteImport.update({
  id: '/organograma',
  path: '/organograma',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentidadeRoute = IdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoriaRoute = AutoriaRouteImport.update({
  id: '/autoria',
  path: '/autoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const ADMCMFRoute = ADMCMFRouteImport.update({
  id: '/ADMCMF',
  path: '/ADMCMF',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ADMCMF': typeof ADMCMFRoute
  '/acompanhar': typeof AcompanharRoute
  '/autoria': typeof AutoriaRoute
  '/documentos': typeof DocumentosRoute
  '/historia': typeof HistoriaRoute
  '/identidade': typeof IdentidadeRoute
  '/inscricao': typeof InscricaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/suporte': typeof SuporteRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ADMCMF': typeof ADMCMFRoute
  '/acompanhar': typeof AcompanharRoute
  '/autoria': typeof AutoriaRoute
  '/documentos': typeof DocumentosRoute
  '/historia': typeof HistoriaRoute
  '/identidade': typeof IdentidadeRoute
  '/inscricao': typeof InscricaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/suporte': typeof SuporteRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ADMCMF': typeof ADMCMFRoute
  '/acompanhar': typeof AcompanharRoute
  '/autoria': typeof AutoriaRoute
  '/documentos': typeof DocumentosRoute
  '/historia': typeof HistoriaRoute
  '/identidade': typeof IdentidadeRoute
  '/inscricao': typeof InscricaoRoute
  '/organograma': typeof OrganogramaRoute
  '/perfil': typeof PerfilRoute
  '/suporte': typeof SuporteRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ADMCMF'
    | '/acompanhar'
    | '/autoria'
    | '/documentos'
    | '/historia'
    | '/identidade'
    | '/inscricao'
    | '/organograma'
    | '/perfil'
    | '/suporte'
    | '/auth/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ADMCMF'
    | '/acompanhar'
    | '/autoria'
    | '/documentos'
    | '/historia'
    | '/identidade'
    | '/inscricao'
    | '/organograma'
    | '/perfil'
    | '/suporte'
    | '/auth/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/ADMCMF'
    | '/acompanhar'
    | '/autoria'
    | '/documentos'
    | '/historia'
    | '/identidade'
    | '/inscricao'
    | '/organograma'
    | '/perfil'
    | '/suporte'
    | '/auth/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ADMCMFRoute: typeof ADMCMFRoute
  AcompanharRoute: typeof AcompanharRoute
  AutoriaRoute: typeof AutoriaRoute
  DocumentosRoute: typeof DocumentosRoute
  HistoriaRoute: typeof HistoriaRoute
  IdentidadeRoute: typeof IdentidadeRoute
  InscricaoRoute: typeof InscricaoRoute
  OrganogramaRoute: typeof OrganogramaRoute
  PerfilRoute: typeof PerfilRoute
  SuporteRoute: typeof SuporteRoute
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organograma': {
      id: '/organograma'
      path: '/organograma'
      fullPath: '/organograma'
      preLoaderRoute: typeof OrganogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identidade': {
      id: '/identidade'
      path: '/identidade'
      fullPath: '/identidade'
      preLoaderRoute: typeof IdentidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autoria': {
      id: '/autoria'
      path: '/autoria'
      fullPath: '/autoria'
      preLoaderRoute: typeof AutoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ADMCMF': {
      id: '/ADMCMF'
      path: '/ADMCMF'
      fullPath: '/ADMCMF'
      preLoaderRoute: typeof ADMCMFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ADMCMFRoute: ADMCMFRoute,
  AcompanharRoute: AcompanharRoute,
  AutoriaRoute: AutoriaRoute,
  DocumentosRoute: DocumentosRoute,
  HistoriaRoute: HistoriaRoute,
  IdentidadeRoute: IdentidadeRoute,
  InscricaoRoute: InscricaoRoute,
  OrganogramaRoute: OrganogramaRoute,
  PerfilRoute: PerfilRoute,
  SuporteRoute: SuporteRoute,
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
